### ISSUE TITLE
A server with the specified hostname could not be found.

### ISSUE THREAD

**Issue by EvgenyKarkan** [gkye/TheMovieDatabaseSwiftWrapper#107]
It seems that the https://api.themoviedb.org is not reachable any longer.
iOS SDK throws the -1003 error with the `A server with the specified hostname could not be found` description.

The https://www.themoviedb.org site also cannot be reached, so it seems something has happened to it.

**Comment by MartinP7r** [comment]
@EvgenyKarkan  

The sites seem fine from my end. Could you confirm that it's not a temporary or local problem on your side?

**Comment by EvgenyKarkan** [comment]
Hmm, yes, it seems that site is not reachable from some specific countries for some reason.
