### ISSUE TITLE
error with swift 3

### ISSUE THREAD

**Issue by piars777** [gkye/TheMovieDatabaseSwiftWrapper#11]
Hi,
I update my project to swift 3 but i encounter some  compilation problem with the pod tmdbswift.
Did you update the pod to support swift 3?

**Comment by gkye** [comment]
No not yet will do it soon. (PRs are always welcome)

**Comment by piars777** [comment]
ok i'll work on this night.

**Comment by piars777** [comment]
i seen thant there is a swift 3 brnch. have you already start? what remains to do?

**Comment by gkye** [comment]
There a weird error going on with one of the protocols which is responsible for creating arrays from the json returned from a call

**Comment by gkye** [comment]
Swift 3 branch is ready to go now, I will update branch and release soon.
