### ISSUE TITLE
Contextual closure type '(Data?, URLResponse?, Error?)

### ISSUE THREAD

**Issue by AegerBorder** [gkye/TheMovieDatabaseSwiftWrapper#19]
Hi,

first of all: thanks for this all!

As a total beginner in both swift and ... eh... this here (;-)) I managed to add everything to an existing project but there were two sections leaving me with error messages from Xcode. One of them was just a usage of outdated code. The warning said:
_"characters is deprecated"_. So I changed it:

old:
`text.characters.count`
new:
`text.count`

I'm having a real pain with the other issue. It's in the file Client.swift

There's the following block:

```
struct Client{
  static func networkRequest(url: String, parameters: [String : AnyObject], completion: @escaping (ClientReturn) -> ()) -> (){
    var cReturn = ClientReturn()
    HTTPRequest.request(url, parameters: parameters){
      rtn in                                       // <- here's the error!
      if rtn.2 == nil{
        let json = try! JSON(data: rtn.0!)
        cReturn.error = nil
        cReturn.json = json
        if(json["page"].exists()){
          cReturn.pageResults = PageResultsMDB.init(results: json)
        }else{
          cReturn.pageResults = nil
        }
      }else{
        cReturn.error = rtn.2 as NSError?
        cReturn.json = nil
        cReturn.pageResults = nil
      }
      completion(cReturn)

    }
```

where it says "rtn in" there's an error message saying:
_"Contextual closure type '(Data?, URLResponse?, Error?) -> ()' expects 3 arguments, but 1 was used in closure body"_.

It advises:
_"Insert ',<#arg#>,<#arg#> '"_

Can anyone tell me what to do here? I've never heard of that. I searched the web for this but I just don't get the cases described there.

Thanks in advance and have a great week

Patrick

P.S.: I'm totally new to GitHub but I thought this might be the right place to ask this. If not, please don't be angry :-/

**Comment by gkye** [comment]
Hello @AegerBorder, I haven't pushed a new update to the CocoaPods yet (will do later today). For now you can use the project directly manually or add `pod 'TMDBSwift', :git => 'https://github.com/gkye/TheMovieDatabaseSwiftWrapper'` to your `Podfile`

**Comment by AegerBorder** [comment]
Hi @gkye, thanks a lot. I updated the Podfile and ran the app without a single warning or error.
Now I have to figure out how to use this thing, haha. Thanks for that quick reply.

**Comment by AegerBorder** [comment]
Hm... I wanted to try one of your examples in movie and put this in my ViewController.swift (apikey isn't real...)

```
MovieMDB.movie(6812cfd24edc653261edf0a135449576, movieID: 7984, language: "de") {
            apiReturn, movie in
            if let movie = movie{
                print(movie.title)
                print(movie.revenue)
                print(movie.genres[0].name)
                print(movie.production_companies?[0].name)
            }
        }
    }
```

There's an error saying:
"Expected a digit after integer literal prefix"

This error describes the letter c after the fourth apikey-number.
It also wants me to add a String after the apikey.

Did I just got it wrong to paste my key over "apikey"?

**Comment by AegerBorder** [comment]
Changed the code a bit to:

```
MovieMDB.movie("6812cfd24edc653261edf0a135449576", movieID: 7984, language: "de") {
            apiReturn, movie in
            if let movie = movie{
                print(movie.title!)
                print(movie.revenue!)
                print(movie.genres[0].name!)
                print(movie.production_companies?[0].name! as Any)
            }
        }
```

Works with this changes but movie.production_companies?[0].name! as Any is "nil"

**Comment by gkye** [comment]
`production_companies` is an optional value (there’s a chance it might be empty)
