### ISSUE TITLE
Extra argument in call (API key)

### ISSUE THREAD

**Issue by lazarevzubov** [gkye/TheMovieDatabaseSwiftWrapper#20]
Hi!

First of all, thank you for the library!

(Actually this is not an issue, it's a question or even a help request.)

Recently I updated my pods and I saw that you released a new version (congratulations!). I noticed in your commits that you removed api key parameters, but there's a great lack of documentation. How can we use it now?
I guess there's some kind of preparatory function but how can I find it?

I used to just call ConfigurationMDB.configuration, TVMDB.popular and SearchMDB.tv. That's it. And all this worked for me.

Thanks in advance for your reply!

**Comment by gkye** [comment]
Hello, 

You no longer need to set an API key for each call, you can use TMDBConfig to set your key.
```swift
TMDBConfig.apikey = "XXXXXX"
```
I'll update the documentation soon. Examples are also available [here ](https://github.com/gkye/TheMovieDatabaseSwiftWrapper/tree/master/TMDBSwiftTests)

**Comment by lazarevzubov** [comment]
@gkye Thank you very much for the fast answer!

**Comment by lazarevzubov** [comment]
@gkye I've tried this way, but TMDBConfig.apikey causes error "Use of unresolved identifier 'TMDBConfig'".

![2017-11-30 21 40 13](https://user-images.githubusercontent.com/21320613/33448506-4b37475a-d617-11e7-8ebd-d0df0f927e95.png)

Nevertheless file Config.swift with TMDBConfig struct is there.

I've changed struct and apikey var access levels to public, and error is gone. Now it works.
