### ISSUE TITLE
Crash if tmdb is unavailable

### ISSUE THREAD

**Issue by hintoz** [gkye/TheMovieDatabaseSwiftWrapper#23]
If TMDB returns a page with error 502, the application crashes, so it tries to parse the answer.
The crash occurs in the `Client.swift` in line `42`

`let json = try! JSON(data: data!)`

Error:
`Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}`

`po response.debugDescription`:
`"Optional(<NSHTTPURLResponse: 0x1c483e8a0> { URL: https://api.themoviedb.org/3/find/tt0258000?api_key=mykey&external_source=imdb_id } { Status Code: 502, Headers {\n    Connection =     (\n        \"keep-alive\"\n    );\n    \"Content-Length\" =     (\n        166\n    );\n    \"Content-Type\" =     (\n        \"text/html\"\n    );\n    Date =     (\n        \"Sat, 17 Feb 2018 23:00:13 GMT\"\n    );\n    Server =     (\n        openresty\n    );\n    \"X-RateLimit-Limit\" =     (\n        40\n    );\n    \"X-RateLimit-Remaining\" =     (\n        39\n    );\n    \"X-RateLimit-Reset\" =     (\n        1518908423\n    );\n} })"`

**Comment by gkye** [comment]
Thanks for reporting this, I'll clean up the force unwraps and return an error where necessary

**Comment by gkye** [comment]
https://github.com/gkye/TheMovieDatabaseSwiftWrapper/commit/1c556b6341f5f51303836cf261e7324d576a171d should fix that, pushing an update to CocoaPods now
