### ISSUE TITLE
Crash with an empty result

### ISSUE THREAD

**Issue by hintoz** [gkye/TheMovieDatabaseSwiftWrapper#25]
The application crashes when an empty list is returned. I attach screenshots from Crashlytics.

1. In the `FindMDB.swift` file on line `123`:
`data = FindMDB.init(json: apiReturn.json!)` <- force unwrapping
Screen: <img width="1070" alt="kp crashlytics firebase console 2018-06-24 15-43-41" src="https://user-images.githubusercontent.com/1215299/41819297-b57e0a4e-77c6-11e8-8825-a8e97b53f042.png">

2. In the `MovieMDB.swift` file on line `27`:
`detailed = MovieDetailedMDB.init(results: apiReturn.json!)`  <- force unwrapping
Screen: <img width="1072" alt="kp crashlytics firebase console 2018-06-24 15-54-23" src="https://user-images.githubusercontent.com/1215299/41819329-4eb1479e-77c7-11e8-8980-681cb1c721c8.png">

Also in this file all methods have force unwrapping.
Thank you for your work.

**Comment by hintoz** [comment]
Another crash in the `TVMDB.swift` file on line `30`:
`data = TVDetailedMDB.init(results: apiReturn.json!)`
Screen: 
<img width="1067" alt="kp crashlytics firebase console 2018-06-24 16-38-51" src="https://user-images.githubusercontent.com/1215299/41819670-1c82ca94-77cd-11e8-81b4-157e3e42b039.png">

**Comment by gkye** [comment]
You're responsible for checking if `apiReturn.json` is `nil` before doing anything with it. (That's why it's optional)

**Comment by gkye** [comment]
Thanks. Mind submitting a PR? No problem if you can't, it'll be fixed soon.
