### ISSUE TITLE
Wiki Documention Not Updated

### ISSUE THREAD

**Issue by Treverr** [gkye/TheMovieDatabaseSwiftWrapper#26]
Hello,

It looks like there is an issue with the Wiki Documentation, when I updated to the newest version I am getting errors with discoverMovies function, looks like things may have moved to a params argument rather than spelled out like they were. Not sure what the params are supposed to look like for your functions.

**Comment by gkye** [comment]
Sorry about that @Treverr, I'll try my best to update the wiki soon. The `MovieMDB.discoverMovies` now takes an array of `DiscoverParam` to make it bit more readable and generic.
ie.
```swift
MovieMDB.discoverMovies(params: [.page(1), .language("en"), .vote_count_gte(10000)], completion: {
			api, movie in
})
``` 

More details [here](https://github.com/gkye/TheMovieDatabaseSwiftWrapper/blob/master/Sources/Models/Discover/Discover.swift#L22)
