### ISSUE TITLE
Application is not building

### ISSUE THREAD

**Issue by iprabhakarpatil** [gkye/TheMovieDatabaseSwiftWrapper#27]
HI, 

I cloned the Repo using the Github desktop client. Am trying to run/build the project. Every time i do this am getting the success message, but the application is not running on any devices. Its displaying "Build Succeeded"
Am using Xcode 9.4.1

**Comment by gkye** [comment]
`TMDBSwift` is a framework and cannot be run directly as an application. Please checkout the example project or integrate it in your project using CocoaPods or manual installation
