### ISSUE TITLE
Replace SwiftyJSON with swift4's Codable

### ISSUE THREAD

**Issue by MartinP7r** [gkye/TheMovieDatabaseSwiftWrapper#33]
Hi, I'm new to the OSS game, but would be interested refactoring SwiftyJSON to Codable.
Are you on that already? If not, I would submit a pull request.

**Comment by gkye** [comment]
Would love to remove the SwiftyJSON dependency, pull requests are welcomed 😄

**Comment by MartinP7r** [comment]
Great. Like I said, I don't have much experience on github, so I might have some questions. I'm very busy during the week, so I'll post something this weekend!
