### ISSUE TITLE
images and video entry point

### ISSUE THREAD

**Issue by piars777** [gkye/TheMovieDatabaseSwiftWrapper#4]
Hi,
Entrypoint for image and video's movie are not yet implemented. Can you make public the method `final func networkRequest(url url: String, parameters: [String : AnyObject], completion: (ClientReturn) -> ()) -> ()`

**Comment by gkye** [comment]
It's prob best that remains internal, I'll add the endpoints later this week or you could submit a pull request if you can do it. Could you give me an example of the query(s) you're trying to run?

**Comment by piars777** [comment]
sorry, i finally found movie and image endpoint. you can close this issue.

**Comment by mrugeshtank** [comment]
I'm facing the same issue.
I'm getting endpoint of images but not getting entry point.
here is my code.

```
MovieMDB.images(movieID: 363088, completion: { (returnClient, images) in
                        let posters = returnClient.json?.dictionary!["posters"]
                        let first = posters?.array![0]
                        print(first)
                    })
```

by running this code I'm getting the following output.

> {
>   "height" : 2000,
>   "vote_average" : 5.46,
>   "aspect_ratio" : 0.66649999999999998,
>   "width" : 1333,
>   "iso_639_1" : "en",
>   "vote_count" : 23,
>   "file_path" : "\/rv1AWImgx386ULjcf62VYaW8zSt.jpg"
> }

could you please help how to load image?

**Comment by MartinP7r** [comment]
Have a look at https://github.com/gkye/TheMovieDatabaseSwiftWrapper/blob/046c668398559ff7dd57d3078bbfa025100ca6d5/Sources/Models/ConfigurationMDB.swift#L34
You have to build the url for your image by combining the base url, an image size and your file_path, e.g. with your image:
http://image.tmdb.org/t/p/w500/rv1AWImgx386ULjcf62VYaW8zSt.jpg
