### ISSUE TITLE
Swift error on simple query

### ISSUE THREAD

**Issue by andreienache97** [gkye/TheMovieDatabaseSwiftWrapper#40]
<img width="861" alt="screenshot 2019-02-13 at 22 53 01" src="https://user-images.githubusercontent.com/33107191/52743283-59f73b80-2fe2-11e9-93ee-49e26c636f73.png">

For some reason I get this error on a simple Discover query. I declared the API_KEY as being a String.

Any ideas how to fix it?

Thanks!

**Comment by piars777** [comment]
discoverMovies method doesn't accept apikey as parameter.
user `TMDBConfig.apikey` to set api key

**Comment by andreienache97** [comment]
Can you give me an example how to set up the API key? I couldn't find any in the documentation.

**Comment by MartinP7r** [comment]
set it like this:
```swift
TMDBConfig.apikey = "YOUR_API_KEY"
```

edit: I hope this solved your problem. Please reopen the issue if not.
