### ISSUE TITLE
Can't find out where to call the authentication methods

### ISSUE THREAD

**Issue by Jsayer7** [gkye/TheMovieDatabaseSwiftWrapper#43]
I see that there is a Client authentication file, however I can't seem to be able to locate them. How do you call these methods?

**Comment by MartinP7r** [comment]
If by authentication you mean setting the api key, you can set it globally by calling  
```swift
TMDBConfig.apikey = "YOUR_API_KEY"
```

**Comment by Jsayer7** [comment]
No, it looks like Client_Authentication.swift contains logic to log into your TMDB account. However, these methods don’t seem to be available.

**Comment by djpearce** [comment]
Authentication APIs are available through 

https://github.com/gkye/TheMovieDatabaseSwiftWrapper/blob/master/Sources/TMDBSwift/Models/Authentication/AuthenticationMDB.swift
