### ISSUE TITLE
Swift Package Manager Support

### ISSUE THREAD

**Issue by iComputerfreak** [gkye/TheMovieDatabaseSwiftWrapper#49]
Since Xcode can now (as of Xcode 11 beta) handle Swift Package Manager dependencies, could you please add support, so that your library can be fetched by the Swift PM insted of using CocoaPods?

**Comment by thomalexandre** [comment]
I would support this, Mostly add a Package.swift file at the source of he repo

// swift-tools-version:5.0
import PackageDescription

let package = Package(
    name: "TheMovieDatabaseSwiftWrapper",
    products: [
        .library(name: "TheMovieDatabaseSwiftWrapper",
                 targets: ["TheMovieDatabaseSwiftWrapper"]),
        .library(name: "TheMovieDatabaseSwiftWrapper-Dynamic",
                 type: .dynamic,
                 targets: ["TheMovieDatabaseSwiftWrapper"]),
    ],
    targets: [
        .target(name: "TheMovieDatabaseSwiftWrapper",
                path: "Sources"),
    ]
)
