### ISSUE TITLE
Wrapper for /trending

### ISSUE THREAD

**Issue by NGromann** [gkye/TheMovieDatabaseSwiftWrapper#53]
There is currently no wrapper for the /trending api.
https://developers.themoviedb.org/3/trending/get-trending

**Comment by gonzo-oin** [comment]
Hello, I think there is a wrapper for the trending API, have a look [here](https://github.com/gkye/TheMovieDatabaseSwiftWrapper/blob/1e0ddb75cc795272f9c78e16cb9e5886296996f2/Sources/Client/Client_Trending.swift#L5)

**Comment by djpearce** [comment]
Trending is wrapped here:

https://github.com/gkye/TheMovieDatabaseSwiftWrapper/blob/master/Sources/TMDBSwift/Models/Trending.swift
