### ISSUE TITLE
tvos  TMDBSwift

### ISSUE THREAD

**Issue by thomalexandre** [gkye/TheMovieDatabaseSwiftWrapper#54]
HI
I try to add pod 'TMDBSwift' for tv os build on cocoad pod, but iit's not running.

`[!] The platform of the target `TiburonVideo_tvOS` (tvOS 13.0) is not compatible with `TMDBSwift (0.5.1)`, which does not support `tvOS`.`

How can it be solved?

Bests

Alex

**Comment by abvijaykumar** [comment]
I am getting the same issue. Not sure what to do to fix it.

**Comment by djpearce** [comment]
Will be fixed in next tag!
