### ISSUE TITLE
API to retrieve the image data?

### ISSUE THREAD

**Issue by tciuro** [gkye/TheMovieDatabaseSwiftWrapper#55]
Hello,

Is there a way to retrieve the image dat? I now I can retrieve the filename (e.g. `/rRgkZUNgD68DD7xDsv1XMmQBjld.jpg`), but there is no clear way to retrieve the actual image. If it's up to client to retrieve it, how is the URL constructed? Let's assume `https://api.themoviedb.org/3/person/1042728`:

      {
        "aspect_ratio": 0.66666666666667,
        "file_path": "/uSSUrSdzH73bcy5hWIB5SZFzuFm.jpg",
        "height": 705,
        "iso_639_1": null,
        "vote_average": 5.312,
        "vote_count": 1,
        "width": 470
      }

These URLs return an error: 🤔

`https://api.themoviedb.org/3/person/1042728/uSSUrSdzH73bcy5hWIB5SZFzuFm.jpg
https://api.themoviedb.org/3/person/1042728/images/uSSUrSdzH73bcy5hWIB5SZFzuFm.jpg`

**Comment by tciuro** [comment]
Ah! So, searching around has led me to the answer:

    http://image.tmdb.org/t/p/w{size}/{path}

Assuming a desired size of `500 points` and a partial path(obtained through the response as mentioned above) of `/uSSUrSdzH73bcy5hWIB5SZFzuFm.jpg` the resulting query is:

    http://image.tmdb.org/t/p/w500//8iVyhmjzUbvAGppkdCZPiyEHSoF.jpg

I found that a size of `500` works quite well on mobile. YMMV, of course.

**Comment by MartinP7r** [comment]
Hi there,

I think you already found this: https://developers.themoviedb.org/3/getting-started/images  

And there's also a thread about image sizes here. https://www.themoviedb.org/talk/53c11d4ec3a3684cf4006400  

Though, as stated in the first link, it's recommended to use the configuration API to get the available file sizes and base URL for images.

**Comment by tciuro** [comment]
Yes, thank you Martin! I had overlooked the configuration API. That helps! BTW, does the API offer a way to retrieve the image, or is this something that needs to be done separately?
